package tool;

import java.io.FileWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

/**
 * Created by Eldath on 2017/1/30 0030.
 *
 * @author Eldath
 */
public class GeneratePropFile {
    private static Map<String, String> schedule = new HashMap<>();
    private static final String nowYear = String.valueOf(LocalDate.now().getYear());
    private static final String nowTimeNotice = "现在是" + LocalDateTime.now().toString() + "\n";

    static {
        schedule.put("12-28T06:06:06", nowTimeNotice + " OPCODE 与 OPCODE ，在冬天的约定 - 1903年的今天，" +
                "计算机之父『冯•诺依曼』降生。\n\"（A）冯.诺依曼可以证明任何事情；\"\"（B）冯.诺依曼所证明的任何事情都是正确的。\"");
        schedule.put("04-28T14:19:17", "Hello, World.");
        schedule.put("01-29T19:03:54", nowTimeNotice + "2016年的今天，是我Avalon的生日。" +
                "\n\" 感谢我的父亲Mojo-Webqq和我的开发者Eldath Ray。 \"");
    }

    public static void main(String[] args) throws Exception {
        Path path = Paths.get(System.getProperty("user.dir") + "/ShowMsg.properties");
        System.out.println("At: " + path.toString());
        Files.deleteIfExists(path);
        Files.createFile(path);
        Properties prop = new Properties();
        prop.putAll(schedule);
        try (FileWriter fw = new FileWriter(path.toFile())) {
            prop.store(fw, "This config file is generated by Avalon to config ShowMsg plugin.");
        }
        // TODO 不能使用Properties！！编码会挂！！
        prop = null;
        prop = new Properties();
        prop.load(Files.newInputStream(path));
        for (Map.Entry stringAPIEntry : prop.entrySet()) {
            String key = nowYear + "-" + stringAPIEntry.getKey();
            String value = (String) stringAPIEntry.getValue();
            System.out.println(LocalDateTime.parse(key).toString() + " : " + new String(value.getBytes(StandardCharsets.US_ASCII)));
        }
    }
}
